version: 2.1

orbs:
  maven: circleci/maven@1.1
  
jobs:
  test:
    docker:
      - image: cimg/openjdk:14.0.2-browsers
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true

workflows:
  maven_test:
    jobs:
      - maven/test
